### ISSUE TITLE
will it support ruby ?

### ISSUE THREAD

**Issue by MwMaki** [alefragnani/vscode-separators#25]
I installed this extension but I can't see any lines, does it support 
1-ruby
2-CoffeeScript files?

Thanks

**Comment by alefragnani** [comment]
Hi @MwMaki ,

The extension doesn't support any particular extension, but in fact, rely on the language extension you have installed (in your case, the Ruby and CoffeScript extensions you have installed), to recognize and draw the separators for each symbol. 

If the extensions you use only does _syntax highlighting_, that's the reason why Separators is not woking.

To recognize if the Ruby and CoffeeScript extensions you have installed will allow **Separators** to work, open any Ruby or CoffeeScript file and run the `Go to Symbol` command, or take a look at the **Outline** panel on Explorer view. If you see symbols there, **Separators** should work as well, otherwise, it won't.

BTW, which extensions do you use for Ruby and CoffeeScript?

Hope this helps

**Comment by MwMaki** [comment]
Thank you, great suggestions,

- I added this extension to enable the symbols on ruby files.
https://marketplace.visualstudio.com/items?itemName=miguel-savignano.ruby-symbols

- I also added this extension to enable the symbols on CoffeeScript files.
https://github.com/yorkxin/vscode-coffeescript-support

great work, thanks
