### ISSUE TITLE
[BUG] - Not detecting all Dart constructions

### ISSUE THREAD

**Issue by JCKodel** [alefragnani/vscode-separators#7]
**Environment/version**

- Extension version: v1.0.2
- VSCode version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:14:40.758Z)
- OS version: Darwin x64 19.6.0

**Steps to reproduce**

Not all Dart/Flutter constructions triggers the separator. Some examples (notice the red arrow indicating where I've deleted my custom `/* -- separator --*/`)

![image](https://user-images.githubusercontent.com/379339/98453672-a67d9580-213a-11eb-9358-226c2e2016e4.png)

(should have separators before `enum` (line 6), before `extension` (line 14) and before each `get` acessor (lines 15 and 32).

![image](https://user-images.githubusercontent.com/379339/98453668-9a91d380-213a-11eb-869c-b2387e0c982d.png)

Before `class` (line 160).

In this file, only one separator was drawn, in the constructor (`const Section(....`). Methods works as well.

Dart has the following constructions that, IMO, requires a separator:

1) Between classes (`class X`, `enum X`, `extension X`, `mixin X`), etc. Dart has no support for interfaces (but has to `abstract class`).

2) Between get/set accessors (It would be amazing if all 3 items could be grouped, but it's fine only before get/set):
```dart
// only one separator here or...
int _privateVar;
// one here
int get privateVar => _privateVar;
// another here
set privateVar(int value) => _privateVar = value;
```

3) Methods (this is the only one working).

Also, in methods, it should consider attributes (in this example, @override belongs to the method itself, so the separator is better to be placed above `@override`):

![image](https://user-images.githubusercontent.com/379339/98453746-623ec500-213b-11eb-939d-3493d5475580.png)

**Comment by alefragnani** [comment]
Hi @JCKodel ,

Right now, the extension only supports `Methods`, `Functions` and `Constructors`, and based on your comments, it appears it is working just fine. 

About the `@override` attribute which can appears above methods, it will depend on changes on the Dart/Flutter extension you use, because it is _that_ extension which provides the _location_ of each symbol, and this extension only _uses_ that information to draw the separators. I don’t _parse_ the source code.

As you already noticed, I’ve opened #2 to expand the kind of symbols which could be supported. At first I thought about addin `Classes`, `Interfaces` and `Enums`, and I’m open for more suggestions. How many, will depend on users feedback. Just keep in mind that it’s not simply a matter of which kind of symbol _some language_ has (you said Dart doesn’t have Interfaces), but how their symbols are mapped to the kind of Symbols VS Code supports (https://code.visualstudio.com/api/references/vscode-api#SymbolKind). It will depend entirely on each Language extension. You can check how these symbols are _translated_ to VS Code symbols, running the `Go to Symbol` Command and typing `:`. It will group the symbols by its kind.

I’ll close this issues because I understand it is working as expected, for the kind of symbols it supposed to do, and the other symbols, are also being requested in #2.

Thanks for your suggestions.

Hope this helps
