### ISSUE TITLE
[QUESTION] - Typescript arrow function

### ISSUE THREAD

**Issue by JRAVILES** [alefragnani/vscode-separators#70]
Hello, is there any way for the extension to recognize Typescript arrow functions?

Thanks in advance

![arrow_function](https://user-images.githubusercontent.com/5407512/164107184-adf04b58-4c45-41cd-95b3-27fc18bb1412.PNG)

**Comment by alefragnani** [comment]
Hi @JRAVILES ,

The extension depends on the Language extension to recognize each symbol. In this case, the TypeScript Language Server, which I suppose you are using the one that comes with VS Code.

If you look at `Outline`, you will notice these arrow functions are not recognized as `functions`, but `symbols` instead. So, the extension will not recognize it. 

You can also use the `Go to Symbol in Editor` command, which opens the Command Palette with an `@` symbol. Simply type `:` and the symbols will be grouped, and you will identify these arrow functions as `symbols`.

To support this, the TypeScript Language Server should be updated/fixed to recognize arrow functions as `functions`. I suggest you to open an issue in VS Code repo itself, since I guess both VS Code and TypeScript team has a close relationship.

Hope this helps

**Comment by JRAVILES** [comment]
Thank tou I will try with MS
