### ISSUE TITLE
[FEATURE] - VBA Language Support | ".bas" and ".frm" file extensions

### ISSUE THREAD

**Issue by lundeen-bryan** [alefragnani/vscode-separators#83]
I would greatly appreciate seeing VBA support for this function as I do a lot of VBA in Excel. This is already such a great Extension so I thank you much for it just as-is. 

VBA uses these keyword symbols:

- Class
- Function
- Sub

Not sure, but you might have to add the keywords "Public" and "Private" too as we typically write "Public Function GetValue()" as an example. 

File extensions are typically ".bas" but I suppose it could also be ".vbs" in some cases and also please add ".frm" for UserForms that have code.

**Comment by alefragnani** [comment]
Hi @lundeen-bryan ,

Thank you for your kind words. I'm glad to know the extension is being helpful.

About VBA support, what are you missing/not working? I mean, this extension relies on _some language extension_ that provides the `Symbols` (the `Outline`), and uses this information to draw the lines. So, if you have some extension that provides `Symbols` for VBA, this extension _should work_. 

The only thing, up until now, this extension needs _special handling_ is while dealing with `callback` functions. This is necessary because each language/extension has its own way to _describe_ a `callback`.

It's been a long time I don't touch VBA source, so I'm not sure which VBA extension you could have installed.

Hope this helps

**Comment by lundeen-bryan** [comment]
Strangely enough it just started working right now. It wasn't working yesterday to show the separators, but I see them now. Maybe it was there all along and just wasn't activated in my machine. If you did make a change today, then it seems to be working great. Either way, thank you and I really do appreciate the effort you are doing with this extension have a good weekend!

**Comment by alefragnani** [comment]
That's great to hear it is working!

I didn't do anything. No new update. Maybe just something related to the VB extension not providing the symbols to some projects. The C# extension presents this behavior, and for some projects it takes too long to analyze and return the symbols.

Anyway, good to know it is working now. Enjoy 😁
