### ISSUE TITLE
[QUESTION] - Still add lines to inline functions

### ISSUE THREAD

**Issue by czinczaar** [alefragnani/vscode-separators#86]
Hello, thanks for this extension:
Even with the following setting, I still have lines for inline functions/callbacks.
![image](https://github.com/alefragnani/vscode-separators/assets/23295465/e54ee187-964b-4752-98f7-54528a08f194)
![image](https://github.com/alefragnani/vscode-separators/assets/23295465/288343f1-dfac-4e89-ae81-19101f892320)

Any idea?
Thanks!

**Comment by alefragnani** [comment]
Hi @czinczaar ,

Could you tell me which language is this, and provide a print screen from the `Outline` view with focus in that function as well?

I'm asking because the `ignoreCallbackInline` setting only works for JavaScript, TypeScript and Lua for now. This happens because each language server describes inline callback differently, and the extension has to parse the description accordingly.

Thank you

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding
