### ISSUE TITLE
[FEATURE] - Add separator with comment

### ISSUE THREAD

**Issue by shayded-exe** [alefragnani/vscode-separators#88]
It would be really nice to be able to specify a comment string that will add a separator.

My use case is code cad scripts in Python. Some of these functions are quite long and can't be broken up into smaller functions. I would like to be able to add a comment like `# ---` (configurable via settings) that inserts a separator.

It would be even cooler if you could specify a dictionary of string -> color mappings.

**Comment by alefragnani** [comment]
Hi @shayded-exe ,

If I understand correctly, if seems you would like to have separators for _comments that follow a pattern_ not Symbols (functions, classes, etc). Am I right?

Thank you

**Comment by shayded-exe** [comment]
@alefragnani Correct, yes

**Comment by alefragnani** [comment]
Have you looked some  _comment related_ extension, like [Better Comments](https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments), [Comment Styler](https://marketplace.visualstudio.com/items?itemName=krembolabs.comment-styler), or others, support this? I mean, I think this feature would better fit on some _comment related_ extension.

I say this mainly because Separators extension was created with focus on _symbols_, and rely entirely on the language extension to detect those symbols. The _comment related_ extensions, on the other hand, focus on comments, and already has parsing and recognition of it inside the text.

**Comment by shayded-exe** [comment]
Those extensions should work. I didn't realize that everything currently relied on the LSP so I get it that adding a text parsing component would be antithetical to the design goals.

**Comment by alefragnani** [comment]
There is nothing _antithetical_ to the design goals on adding such feature, it's just a matter of extension's objective and available engines. 

To add separators to comments, it would be required to add a new text parsing engine and a new color mapping. Those extensions, being focused on _comments_, already provides proper text parsing engines and I think they could improve their decorations with separator like lines easily.

It could be added here? Maybe yes. But I think it would be easier on those extensions.
