### ISSUE TITLE
[QUESTION] - Can I customize line start string for separator?

### ISSUE THREAD

**Issue by xgdgsc** [alefragnani/vscode-separators#89]
I would want to set line starting with `##` as a separator indicator.

**Comment by alefragnani** [comment]
Hi @xgdgsc ,

Unfortunately, this is not supported. The separators are limited to [CSS Border styles](https://www.w3schools.com/css/css_border.asp).

Hope this helps

**Comment by xgdgsc** [comment]
I don' t mean the style of the line. I want to customize it to add that line before line starting with `##`, which is an indicator of code cell in the vscode-julia extension.

**Comment by alefragnani** [comment]
I don’t know Julia lang, so, I would like to know if those _code cells_ are recognized as **Symbols** (methods, functions, etc) or just regular/organized code? 

* If yes, and these `##` lines are locate above as _comments_ I think your request is a duplicate of #21 . 
* If not, and these cells are just _regular/organized code_, then this wouldn’t be available. In fact I guess the extension wouldn’t work at all, since the extension relies on language extensions to _tell_ the symbols.

Could you provide prints of pieces of code on how the extension is drawing the lines and how you would like it to be? And please, leave the `Outline` view opened, so I could identify the _symbols_ that the language extension exposes.

Thank you

**Comment by xgdgsc** [comment]
Thanks. It seems it works with julai function/structs. So it' s doable if the julia extension adds ## as one kind of section separator. So there' s nothing needed to do here.
