### ISSUE TITLE
[FEATURE] - Add an option of separator opacity

### ISSUE THREAD

**Issue by Stehsaer** [alefragnani/vscode-separators#96]
I personally prefer separators with less opacity than completely opaque. However, tweaking and setting the colors one by one is quite annoying. So I suggest adding an option to determine the opacity of separators.

**Comment by Stehsaer** [comment]
Is it viable to manually parse and combine hex values as strings?

For example, `#ff0000` and opacity of 50%, turn 50% into hex value of 0x80, and combine into `#ff000080`

**Comment by Stehsaer** [comment]
If we can grab the colors and generate the separators using hex color string, this is theoretically viable. If possible, please point out the related code and I'm glad to contribute.

**Comment by alefragnani** [comment]
There is no way to _load_ values from a `ThemeColor`, so if a theme extension defines any color contributed by the extension, you won't be able to parse. That's the missing API I described above.

Parse values _overridden_ by users in `workbench.colorCustomizations` is possible, for sure, as it is a user setting like any other, but it won't work if the users doesn't override the value. The reason I don't use this approach is because it only works for the users that has changed the value.

If you want to play with it, feel free. The file that handles the colors and creation of decoration is `decoration.ts` . Maybe you find and alternative to this, or the `getConfiguration` API has changed and will provide more info that before. 

Hope this helps
