### ISSUE TITLE
[FEATURE] - Add translation to Simplified Chinese

### ISSUE THREAD

**Issue by Stehsaer** [alefragnani/vscode-separators#97]
I hope to add Simplified Chinese language support for this extension, and I need some more info about how to add a translation.

**Comment by alefragnani** [comment]
Hi @Stehsaer ,

There are up to three different resources to be translated in VS Code extensions, and the Separators extension uses only two:

* `package.nls.xxx.json`: commands, menus and settings
* `./l10n/bundle.l10n.xxx.json`: messages and other strings located inside the source code 

> an oficial sample is located here https://github.com/microsoft/vscode-extension-samples/tree/main/l10n-sample

Simply create a new file named with the language-id you want (instead of the _xxx_), on the same location.

Follow the `CONTRIBUTING.md` file to know how to build and debug the extension, in order to test your translation.

Hope this helps

**Comment by Stehsaer** [comment]
Is it correct that, what I need to do is:
1. Fork the repos based on the main branch and create a new branch in the forked repos
2. Create new localization files and commit
3. Create a pull request

I'm quite new to contributing in GitHub.

**Comment by alefragnani** [comment]
Yes, it is correct, and your PR was already merged

Thank you

**Comment by Stehsaer** [comment]
Literally, my first ever contribution to a public repository. Thanks for your guidance and also for creating this extension!

**Comment by alefragnani** [comment]
You did great! And I'm glad to know you like the extension.
